# NOVA RICS Open Lab 🧊, MIT license

name: 🐛 Bug Report
# title: " "
description: Problems with the Open Modular Controller
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Open Modular Controller 🐛 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Open Modular Controller [issues](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Open Modular Controller Component
      description: |
        Please select the part of Open Modular Controller where you found the bug.
      multiple: true
      options:
        - "Circuit Code"
        - "Hardware"
        - "Integrations"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - OS: Ubuntu 20.04
        - Arduino IDE: 2.3.3
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a minimal reproducible example and accessible datasets, libraries, components, etc.
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/pulls) (PR) to help improve the Open Modular Controller for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Open Modular Controller [Contributing Guide](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/blob/main/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!