blank_issues_enabled: false
contact_links:
  - name: 📄 Docs
    url: https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/tree/main/docs
    about: View Open Modular Controller Docs.
  - name: 💬 Forum
    url: https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/discussions
    about: Ask on Open Modular Controller Discussions.
