# NOVA RICS Open Lab ðŸ§Š, MIT license

name: â“ Question
description: Ask a question about the Open Modular Controller Project
# title: " "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a Open Modular Controller â“ Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/issues) and [discussions](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the YOLOv5 [issues](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/issues) and [discussions](https://github.com/NOVA-RICS-Open-Lab/open-modular-controller/discussions) and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?